imports:
- path: template.py
resources:
- name: citrix-adc-2nic-deployment
  type: template.py
  properties:
   #The Google Region where the Citrix ADC would be deployed. Example: us-east1
   region: "<region>"
   #The availability zone in the region where the Citrix ADC would be deployed.
   #Example: us-east1-b
   google_zone: "<google_zone>"
   #The network to deploy the Citrix ADC
   mgmt_network: "<management_network>"
   #Subnet for the management interface
   mgmt_subnet: "<management_subnet>"
   # Provide the CIDR (usually Public) to access the management interface of the Citrix ADC
   # You can get your public IP from https://www.whatismyip.com/ OR running `curl ifconfig.me`
   # Example: "100.100.10.10/32" OR "100.100.0.0/16"
   restricted_management_access_cidr: ""
   #Ports to open to process management traffic
   mgmt_ports:
       - "22"
       - "80"
       - "443"
   #Network for the nic used to handle client/server side traffic
   traffic_network: "<traffic_network>"
   #Subnet in the specified network to handle client/server side traffic
   traffic_subnet: "<traffic_subnet>"
   #Ports to open to process client/server traffic
   traffic_ports:
       - "80"
       - "22"
   #The Citrix ADC image name
   image_name: "citrix-adc-vpx-byol-14-1-12-30"
   #The project name where the image is hosted
   image_project_id: "citrix-master-project"
   #The instance type to deploy the Citrix ADC instance Example: n1-standard-4
   instance_type: "<instance_type>"
   #The public key used for authenticating into the Citrix ADC.
   #Specify values separated by \n to specify more than one user.
   #Set it to "" if you wish to specify no key
   ssh_public_key: "[USERNAME_1]:ssh-rsa [EXISTING_KEY] [USERNAME_1]"
   #Specify a service account. If not, leave the field blank.
   service_account: "<service_account>"
   #Enter "yes" if you would like a public ip to be associated to the NIC.
   assign_public_ip: "<yes/no>"
